### ISSUE TITLE
Unable to import images

### ISSUE THREAD

**Issue by Arpitgoyalgg** [zaydek/retro#15]
I am trying to add images to my app but the import statement says `error: No loader is configured for ".png" files`. This is the same for other file formats too.

**Comment by zaydek** [comment]
Thanks for opening an issue!

Images are not currently supported out of the box the way you might be used to with Create React App. That being said, you can do this: Put images in `www/images`, for example you can name `images` to whatever you want, or even just put an image in `www`. Then you can just reference your image as a `src` like `<img src="/www/images/my-image.jpg" />`. What’s happening is that your `www` folder hosts static assets and then your code you just reference the hosted asset.

Technically, you might be able to add a plugin to get Retro to work with imported `.jpg` and `.png` files, for example, but for now this is not support without a plugin.

**Comment by Arpitgoyalgg** [comment]
I just tried it but still not working. No errors though. I am doing `<img src="../www/images/amazon.png" />` from my App.js and the image is in `www/images/`.

**Comment by zaydek** [comment]
Try removing the `../`. Retro servers `out` as the top-level directory. Reference repro is here: https://github.com/zaydek/retro-test-image.
